Repository imhuso/cunzhi, pull requests merged in 2025-06, with the labels that each got.

#9 fix: brew url version
  .github/workflows/release.yml
Labels: size/M

#10 feat: implement manual approval for auto-release workflow
  .github/workflows/auto-release.yml
Labels: size/M, release

#12 docs: add some errors prompts
  .github/workflows/auto-release.yml
  README.md
Labels: size/L

#13 feat: Add custom API URL support for Telegram Bot proxy configuration
  Cargo.lock
  src/frontend/components/settings/TelegramSettings.vue
  src/rust/config/settings.rs
  src/rust/telegram/commands.rs
  src/rust/telegram/core.rs
  src/rust/telegram/integration.rs
  src/rust/telegram/mcp_handler.rs
Labels: size/L

#14 fix: Fix exit warning display issue and optimize code structure
  .github/workflows/update-homebrew.yml
  Cargo.lock
  docs/auto-release-workflow.md
  src/frontend/App.vue
  src/frontend/components/settings/TelegramSettings.vue
  src/frontend/composables/useAppInitialization.ts
  src/frontend/composables/useAudioManager.ts
  src/frontend/composables/useExitWarning.ts
  src/frontend/composables/useMcpHandler.ts
  src/frontend/composables/useSettings.ts
  src/rust/app/builder.rs
  src/rust/app/cli.rs
  src/rust/app/commands.rs
  src/rust/app/mod.rs
  src/rust/app/setup.rs
  src/rust/config/settings.rs
  src/rust/constants/app.rs
  src/rust/constants/validation.rs
  src/rust/lib.rs
  src/rust/main.rs
  src/rust/mcp/handlers/popup.rs
  src/rust/mcp/server.rs
  src/rust/mcp/tools/memory/manager.rs
  src/rust/telegram/commands.rs
  src/rust/telegram/core.rs
  src/rust/telegram/mcp_handler.rs
  src/rust/ui/audio_assets.rs
  src/rust/ui/commands.rs
  src/rust/ui/exit.rs
  src/rust/ui/mod.rs
  src/rust/ui/window_events.rs
Labels: size/XXL

#15 feat: Major refactoring and feature enhancements
  Cargo.lock
  Cargo.toml
  docs/RELEASE.md
  docs/auto-release-workflow.md
  src/frontend/App.vue
  src/frontend/components/AppContent.vue
  src/frontend/components/layout/LayoutWrapper.vue
  src/frontend/components/popup/PopupActions.vue
  src/frontend/components/popup/PopupTransition.vue
  src/frontend/components/popup/index.ts
  src/frontend/composables/useAppInitialization.ts
  src/frontend/composables/useAppManager.ts
  src/frontend/composables/useAppState.ts
  src/frontend/composables/useEventHandlers.ts
  src/frontend/composables/useExitWarning.ts
  src/frontend/composables/useMcpHandler.ts
  src/frontend/composables/usePopup.ts
  src/frontend/composables/usePopupManager.ts
  src/frontend/composables/useSettings.ts
  src/frontend/composables/useTransition.ts
  src/frontend/types/popup.d.ts
  src/rust/app/builder.rs
  src/rust/app/setup.rs
  src/rust/assets/resources/dengyixia[等一下].mp3
  src/rust/ui/global_shortcuts.rs
  src/rust/ui/mod.rs
  src/rust/ui/window_events.rs
  tauri.conf.json
Labels: size/XXL

#27 Fix Windows path encoding issue for memory function (#24)
  Cargo.lock
  Cargo.toml
  src/frontend/components/AppContent.vue
  src/frontend/components/popup/PopupHeader.vue
  src/rust/mcp/tools/memory/manager.rs
  src/rust/mcp/utils/common.rs
  uno.config.ts
Labels: size/M

#28 Fix Ubuntu 24 compatibility
  .github/workflows/release.yml
Labels: size/XS
